version: '2'

services:
  app:
    image: 'ggulhan/girish_gulhane.jar:latest'
    build:
      context: .
    container_name: app1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db1    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employees
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Giri750
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Giri750
      - POSTGRES_DB=employees
    expose:
      - "5432:5432" 
  dbsaaa:
    driver: local
